version: "3.8"

services:
    app:
        image: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - mysql

    mysql:
        image: mysql:8
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root # Password for the root user
            MYSQL_DATABASE: ${DB_DATABASE}
            # Removed MYSQL_USER and MYSQL_PASSWORD
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
